version: 2
updates:

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin.*"
          - "com.google.devtools.ksp"

  - package-ecosystem: "gradle"
    directory: "/experiments/dokka-multilevel"
    schedule:
      interval: "daily"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin.*"
          - "com.google.devtools.ksp"

  - package-ecosystem: "maven"
    directory: "/demo-projects/fibonacci"
    schedule:
      interval: "daily"
    groups:
      postgresql:
        patterns:
          - "*postgresql*"
      maven:
        patterns:
          - "*maven*"
      kotlin:
        patterns:
          - "*kotlin*"
