version: 2
updates:

  - package-ecosystem: "gradle"
    directory: "/talks"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/you-tube-sessions"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/experiments"
    schedule:
      interval: "daily"
